FROM node:lts-slim

RUN npm i -g \
      @anthropic-ai/claude-code@latest \
      @openai/codex@latest \
      @getpaseo/cli@latest

COPY --chmod=755 ai-harness/* /usr/local/bin/

ENTRYPOINT ["entrypoint"]