FROM node:lts-slim

RUN npm i -g \
      @anthropic-ai/claude-code@latest \
      @openai/codex@latest \
      opencode-ai \
      @getpaseo/cli@latest 
      @earendil-works/pi-coding-agent@latest

COPY --chmod=755 ai-harness/* /usr/local/bin/

ENTRYPOINT ["entrypoint"]
